/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_window_X11Window */

#ifndef _Included_twilight_bgfx_window_X11Window
#define _Included_twilight_bgfx_window_X11Window
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nSetMaximized(
		JNIEnv* env, jobject self, jboolean);

JNIEXPORT jint JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nGetAbsoluteX(
		JNIEnv* env, jobject self);

JNIEXPORT jint JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nGetAbsoluteY(
		JNIEnv* env, jobject self);

JNIEXPORT jlong JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nGetId(
		JNIEnv* env, jobject self);

JNIEXPORT jlong JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_ngetNativeHandle(
		JNIEnv* env, jobject, jlong);

JNIEXPORT jint JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_ngetSDLWindowId(
		JNIEnv* env, jobject, jlong);

/*
 * Class:     twilight_bgfx_window_X11Window
 * Method:    createWindow
 * Signature: (Ll33tlabs/twilight/bgfx/window/X11Display;)J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_createWindow
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     twilight_bgfx_window_X11Window
 * Method:    destroyWindow
 * Signature: (Ll33tlabs/twilight/bgfx/window/X11Display;)J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_destroyWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_window_X11Window
 * Method:    initBGFX
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_initBGFX
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Window
 * Method:    nSetPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nSetPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     twilight_bgfx_window_X11Window
 * Method:    nGetWindowRect
 * Signature: ()Ll33tlabs/twilight/bgfx/window/Window/Rect;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nGetWindowRect
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Window
 * Method:    nSetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nSetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     twilight_bgfx_window_X11Window
 * Method:    nSetVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nSetVisible
  (JNIEnv *, jobject, jboolean);

/**
 *
 */
void JNICALL Java_twilight_bgfx_window_sdl_SDLWindow_nRaise
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
