/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_BGFX */

#ifndef _Included_twilight_bgfx_BGFX
#define _Included_twilight_bgfx_BGFX
#ifdef __cplusplus
extern "C" {
#endif
#undef twilight_bgfx_BGFX_BGFX_STATE_RGB_WRITE
#define twilight_bgfx_BGFX_BGFX_STATE_RGB_WRITE 1LL
#undef twilight_bgfx_BGFX_BGFX_STATE_ALPHA_WRITE
#define twilight_bgfx_BGFX_BGFX_STATE_ALPHA_WRITE 2LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_WRITE
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_WRITE 4LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_LESS
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_LESS 16LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_LEQUAL
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_LEQUAL 32LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_EQUAL
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_EQUAL 48LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_GEQUAL
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_GEQUAL 64LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_GREATER
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_GREATER 80LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_NOTEQUAL
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_NOTEQUAL 96LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_NEVER
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_NEVER 112LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_ALWAYS
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_ALWAYS 128LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_SHIFT
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_SHIFT 4LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_MASK
#define twilight_bgfx_BGFX_BGFX_STATE_DEPTH_TEST_MASK 240LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_ZERO
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_ZERO 4096LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_ONE
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_ONE 8192LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_SRC_COLOR
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_SRC_COLOR 12288LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_SRC_COLOR
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_SRC_COLOR 16384LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_SRC_ALPHA
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_SRC_ALPHA 20480LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_SRC_ALPHA
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_SRC_ALPHA 24576LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_DST_ALPHA
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_DST_ALPHA 28672LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_DST_ALPHA
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_DST_ALPHA 32768LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_DST_COLOR
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_DST_COLOR 36864LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_DST_COLOR
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_DST_COLOR 40960LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_SRC_ALPHA_SAT
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_SRC_ALPHA_SAT 45056LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_FACTOR
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_FACTOR 49152LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_FACTOR
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_INV_FACTOR 53248LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_SHIFT
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_SHIFT 12LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_MASK
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_MASK 268431360LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnSUB
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnSUB 268435456LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnREVSUB
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnREVSUB 536870912LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnMIN
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnMIN 805306368LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnMAX
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnMAX 1073741824LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnSHIFT
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnSHIFT 28LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnMASK
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_EQUATIOnMASK 16911433728LL
#undef twilight_bgfx_BGFX_BGFX_STATE_BLEND_INDEPENDENT
#define twilight_bgfx_BGFX_BGFX_STATE_BLEND_INDEPENDENT 17179869184LL
#undef twilight_bgfx_BGFX_BGFX_STATE_CULL_CW
#define twilight_bgfx_BGFX_BGFX_STATE_CULL_CW 68719476736LL
#undef twilight_bgfx_BGFX_BGFX_STATE_CULL_CCW
#define twilight_bgfx_BGFX_BGFX_STATE_CULL_CCW 137438953472LL
#undef twilight_bgfx_BGFX_BGFX_STATE_CULL_SHIFT
#define twilight_bgfx_BGFX_BGFX_STATE_CULL_SHIFT 36LL
#undef twilight_bgfx_BGFX_BGFX_STATE_CULL_MASK
#define twilight_bgfx_BGFX_BGFX_STATE_CULL_MASK 206158430208LL
#undef twilight_bgfx_BGFX_BGFX_STATE_ALPHA_REF_SHIFT
#define twilight_bgfx_BGFX_BGFX_STATE_ALPHA_REF_SHIFT 40LL
#undef twilight_bgfx_BGFX_BGFX_STATE_ALPHA_REF_MASK
#define twilight_bgfx_BGFX_BGFX_STATE_ALPHA_REF_MASK 280375465082880LL
#undef twilight_bgfx_BGFX_BGFX_STATE_PT_TRISTRIP
#define twilight_bgfx_BGFX_BGFX_STATE_PT_TRISTRIP 281474976710656LL
#undef twilight_bgfx_BGFX_BGFX_STATE_PT_LINES
#define twilight_bgfx_BGFX_BGFX_STATE_PT_LINES 562949953421312LL
#undef twilight_bgfx_BGFX_BGFX_STATE_PT_POINTS
#define twilight_bgfx_BGFX_BGFX_STATE_PT_POINTS 844424930131968LL
#undef twilight_bgfx_BGFX_BGFX_STATE_PT_SHIFT
#define twilight_bgfx_BGFX_BGFX_STATE_PT_SHIFT 48LL
#undef twilight_bgfx_BGFX_BGFX_STATE_PT_MASK
#define twilight_bgfx_BGFX_BGFX_STATE_PT_MASK 844424930131968LL
#undef twilight_bgfx_BGFX_BGFX_STATE_POINT_SIZE_SHIFT
#define twilight_bgfx_BGFX_BGFX_STATE_POINT_SIZE_SHIFT 52LL
#undef twilight_bgfx_BGFX_BGFX_STATE_POINT_SIZE_MASK
#define twilight_bgfx_BGFX_BGFX_STATE_POINT_SIZE_MASK 1148417904979476480LL
#undef twilight_bgfx_BGFX_BGFX_STATE_MSAA
#define twilight_bgfx_BGFX_BGFX_STATE_MSAA 1152921504606846976LL
#undef twilight_bgfx_BGFX_BGFX_STATE_RESERVED_MASK
#define twilight_bgfx_BGFX_BGFX_STATE_RESERVED_MASK -2305843009213693952LL
#undef twilight_bgfx_BGFX_BGFX_STATE_NONE
#define twilight_bgfx_BGFX_BGFX_STATE_NONE 0LL
#undef twilight_bgfx_BGFX_BGFX_STATE_MASK
#define twilight_bgfx_BGFX_BGFX_STATE_MASK -1LL
#undef twilight_bgfx_BGFX_BGFX_STATE_DEFAULT
#define twilight_bgfx_BGFX_BGFX_STATE_DEFAULT 1152921573326323735LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_FUNC_REF_SHIFT
#define twilight_bgfx_BGFX_BGFX_STENCIL_FUNC_REF_SHIFT 0LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_FUNC_REF_MASK
#define twilight_bgfx_BGFX_BGFX_STENCIL_FUNC_REF_MASK 255LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_FUNC_RMASK_SHIFT
#define twilight_bgfx_BGFX_BGFX_STENCIL_FUNC_RMASK_SHIFT 8LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_FUNC_RMASK_MASK
#define twilight_bgfx_BGFX_BGFX_STENCIL_FUNC_RMASK_MASK 65280LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_LESS
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_LESS 65536LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_LEQUAL
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_LEQUAL 131072LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_EQUAL
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_EQUAL 196608LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_GEQUAL
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_GEQUAL 262144LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_GREATER
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_GREATER 327680LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_NOTEQUAL
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_NOTEQUAL 393216LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_NEVER
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_NEVER 458752LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_ALWAYS
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_ALWAYS 524288LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_SHIFT
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_SHIFT 16LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_TEST_MASK
#define twilight_bgfx_BGFX_BGFX_STENCIL_TEST_MASK 983040LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_ZERO
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_ZERO 0LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_KEEP
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_KEEP 1048576LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_REPLACE
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_REPLACE 2097152LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_INCR
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_INCR 3145728LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_INCRSAT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_INCRSAT 4194304LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_DECR
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_DECR 5242880LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_DECRSAT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_DECRSAT 6291456LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_INVERT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_INVERT 7340032LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_SHIFT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_SHIFT 20LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_MASK
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_S_MASK 15728640LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_ZERO
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_ZERO 0LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_KEEP
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_KEEP 16777216LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_REPLACE
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_REPLACE 33554432LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_INCR
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_INCR 50331648LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_INCRSAT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_INCRSAT 67108864LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_DECR
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_DECR 83886080LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_DECRSAT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_DECRSAT 100663296LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_INVERT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_INVERT 117440512LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_SHIFT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_SHIFT 24LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_MASK
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_FAIL_Z_MASK 251658240LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_ZERO
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_ZERO 0LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_KEEP
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_KEEP 268435456LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_REPLACE
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_REPLACE 536870912LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_INCR
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_INCR 805306368LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_INCRSAT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_INCRSAT 1073741824LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_DECR
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_DECR 1342177280LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_DECRSAT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_DECRSAT 1610612736LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_INVERT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_INVERT 1879048192LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_SHIFT
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_SHIFT 28LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_MASK
#define twilight_bgfx_BGFX_BGFX_STENCIL_OP_PASS_Z_MASK 4026531840LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_NONE
#define twilight_bgfx_BGFX_BGFX_STENCIL_NONE 0LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_MASK
#define twilight_bgfx_BGFX_BGFX_STENCIL_MASK 4294967295LL
#undef twilight_bgfx_BGFX_BGFX_STENCIL_DEFAULT
#define twilight_bgfx_BGFX_BGFX_STENCIL_DEFAULT 0LL
#undef twilight_bgfx_BGFX_BGFX_CLEAR_NONE
#define twilight_bgfx_BGFX_BGFX_CLEAR_NONE 0LL
#undef twilight_bgfx_BGFX_BGFX_CLEAR_COLOR_BIT
#define twilight_bgfx_BGFX_BGFX_CLEAR_COLOR_BIT 1LL
#undef twilight_bgfx_BGFX_BGFX_CLEAR_DEPTH_BIT
#define twilight_bgfx_BGFX_BGFX_CLEAR_DEPTH_BIT 2LL
#undef twilight_bgfx_BGFX_BGFX_CLEAR_STENCIL_BIT
#define twilight_bgfx_BGFX_BGFX_CLEAR_STENCIL_BIT 4LL
#undef twilight_bgfx_BGFX_BGFX_DEBUG_NONE
#define twilight_bgfx_BGFX_BGFX_DEBUG_NONE 0LL
#undef twilight_bgfx_BGFX_BGFX_DEBUG_WIREFRAME
#define twilight_bgfx_BGFX_BGFX_DEBUG_WIREFRAME 1LL
#undef twilight_bgfx_BGFX_BGFX_DEBUG_IFH
#define twilight_bgfx_BGFX_BGFX_DEBUG_IFH 2LL
#undef twilight_bgfx_BGFX_BGFX_DEBUG_STATS
#define twilight_bgfx_BGFX_BGFX_DEBUG_STATS 4LL
#undef twilight_bgfx_BGFX_BGFX_DEBUG_TEXT
#define twilight_bgfx_BGFX_BGFX_DEBUG_TEXT 8LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_NONE
#define twilight_bgfx_BGFX_BGFX_TEXTURE_NONE 0LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_U_MIRROR
#define twilight_bgfx_BGFX_BGFX_TEXTURE_U_MIRROR 1LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_U_CLAMP
#define twilight_bgfx_BGFX_BGFX_TEXTURE_U_CLAMP 2LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_U_SHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_U_SHIFT 0LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_U_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_U_MASK 3LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_V_MIRROR
#define twilight_bgfx_BGFX_BGFX_TEXTURE_V_MIRROR 4LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_V_CLAMP
#define twilight_bgfx_BGFX_BGFX_TEXTURE_V_CLAMP 8LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_V_SHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_V_SHIFT 2LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_V_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_V_MASK 12LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_W_MIRROR
#define twilight_bgfx_BGFX_BGFX_TEXTURE_W_MIRROR 16LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_W_CLAMP
#define twilight_bgfx_BGFX_BGFX_TEXTURE_W_CLAMP 32LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_W_SHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_W_SHIFT 4LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_W_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_W_MASK 48LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MInPOINT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MInPOINT 64LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MInANISOTROPIC
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MInANISOTROPIC 128LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MInSHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MInSHIFT 6LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MInMASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MInMASK 192LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MAG_POINT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MAG_POINT 256LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MAG_ANISOTROPIC
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MAG_ANISOTROPIC 512LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MAG_SHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MAG_SHIFT 8LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MAG_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MAG_MASK 768LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MIP_POINT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MIP_POINT 1024LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MIP_SHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MIP_SHIFT 10LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_MIP_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_MIP_MASK 1024LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT 4096LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_X2
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_X2 8192LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_X4
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_X4 12288LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_X8
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_X8 16384LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_X16
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_X16 20480LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_SHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_SHIFT 12LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MSAA_MASK 28672LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT_BUFFER_ONLY
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT_BUFFER_ONLY 32768LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RT_MASK 61440LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_LESS
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_LESS 65536LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_LEQUAL
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_LEQUAL 131072LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_EQUAL
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_EQUAL 196608LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_GEQUAL
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_GEQUAL 262144LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_GREATER
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_GREATER 327680LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_NOTEQUAL
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_NOTEQUAL 393216LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_NEVER
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_NEVER 458752LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_ALWAYS
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_ALWAYS 524288LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_SHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_SHIFT 16LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_COMPARE_MASK 983040LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RESERVED_SHIFT
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RESERVED_SHIFT 24LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_RESERVED_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_RESERVED_MASK 4278190080LL
#undef twilight_bgfx_BGFX_BGFX_TEXTURE_SAMPLER_BITS_MASK
#define twilight_bgfx_BGFX_BGFX_TEXTURE_SAMPLER_BITS_MASK 985087LL
#undef twilight_bgfx_BGFX_BGFX_RESET_NONE
#define twilight_bgfx_BGFX_BGFX_RESET_NONE 0LL
#undef twilight_bgfx_BGFX_BGFX_RESET_FULLSCREEN
#define twilight_bgfx_BGFX_BGFX_RESET_FULLSCREEN 1LL
#undef twilight_bgfx_BGFX_BGFX_RESET_FULLSCREEnSHIFT
#define twilight_bgfx_BGFX_BGFX_RESET_FULLSCREEnSHIFT 0LL
#undef twilight_bgfx_BGFX_BGFX_RESET_FULLSCREEnMASK
#define twilight_bgfx_BGFX_BGFX_RESET_FULLSCREEnMASK 1LL
#undef twilight_bgfx_BGFX_BGFX_RESET_MSAA_X2
#define twilight_bgfx_BGFX_BGFX_RESET_MSAA_X2 16LL
#undef twilight_bgfx_BGFX_BGFX_RESET_MSAA_X4
#define twilight_bgfx_BGFX_BGFX_RESET_MSAA_X4 32LL
#undef twilight_bgfx_BGFX_BGFX_RESET_MSAA_X8
#define twilight_bgfx_BGFX_BGFX_RESET_MSAA_X8 48LL
#undef twilight_bgfx_BGFX_BGFX_RESET_MSAA_X16
#define twilight_bgfx_BGFX_BGFX_RESET_MSAA_X16 64LL
#undef twilight_bgfx_BGFX_BGFX_RESET_MSAA_SHIFT
#define twilight_bgfx_BGFX_BGFX_RESET_MSAA_SHIFT 4LL
#undef twilight_bgfx_BGFX_BGFX_RESET_MSAA_MASK
#define twilight_bgfx_BGFX_BGFX_RESET_MSAA_MASK 112LL
#undef twilight_bgfx_BGFX_BGFX_RESET_VSYNC
#define twilight_bgfx_BGFX_BGFX_RESET_VSYNC 128LL
#undef twilight_bgfx_BGFX_BGFX_RESET_CAPTURE
#define twilight_bgfx_BGFX_BGFX_RESET_CAPTURE 256LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC1
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC1 1LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC2
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC2 2LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC3
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC3 4LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC4
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC4 8LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC5
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_BC5 16LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_ETC1
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_ETC1 32LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_ETC2
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_ETC2 64LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_ETC2A
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_ETC2A 128LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_ETC2A1
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_ETC2A1 256LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC12
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC12 512LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC14
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC14 1024LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC14A
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC14A 2048LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC12A
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC12A 4096LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC22
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC22 8192LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC24
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_PTC24 16384LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D16
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D16 32768LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D24
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D24 65536LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D24S8
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D24S8 131072LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D32
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D32 262144LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D16F
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D16F 524288LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D24F
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D24F 1048576LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D32F
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D32F 2097152LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D0S8
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_FORMAT_D0S8 4194304LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_COMPARE_LEQUAL
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_COMPARE_LEQUAL 16777216LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_COMPARE_ALL
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_COMPARE_ALL 50331648LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_3D
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_3D 67108864LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_VERTEX_ATTRIB_HALF
#define twilight_bgfx_BGFX_BGFX_CAPS_VERTEX_ATTRIB_HALF 134217728LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_INSTANCING
#define twilight_bgfx_BGFX_BGFX_CAPS_INSTANCING 268435456LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_RENDERER_MULTITHREADED
#define twilight_bgfx_BGFX_BGFX_CAPS_RENDERER_MULTITHREADED 536870912LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_FRAGMENT_DEPTH
#define twilight_bgfx_BGFX_BGFX_CAPS_FRAGMENT_DEPTH 1073741824LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_BLEND_INDEPENDENT
#define twilight_bgfx_BGFX_BGFX_CAPS_BLEND_INDEPENDENT 2147483648LL
#undef twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_DEPTH_MASK
#define twilight_bgfx_BGFX_BGFX_CAPS_TEXTURE_DEPTH_MASK 8355840LL

JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nfreeTransientIndexBuffers
  (JNIEnv* env, jobject self, jlongArray bufferPointers);

JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nfreeTransientVertexBuffers
  (JNIEnv* env, jobject self, jlongArray bufferPointers);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateFrameBuffer
 * Signature: (IILl33tlabs/twilight/bgfx/BGFX/TextureFormat;J)Ll33tlabs/twilight/bgfx/BGFX/FrameBufferHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateFrameBuffer__IILtwilight_bgfx_TextureFormat_2J
  (JNIEnv *, jobject, jint, jint, jobject, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateFrameBuffer
 * Signature: (SLl33tlabs/twilight/bgfx/BGFX/TextureHandle;Z)Ll33tlabs/twilight/bgfx/BGFX/FrameBufferHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateFrameBuffer__I_3IZ
  (JNIEnv *, jobject, jint, jintArray, jboolean);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateFrameBuffer
 * Signature: (IILl33tlabs/twilight/bgfx/BGFX/TextureFormat;J)Ll33tlabs/twilight/bgfx/BGFX/FrameBufferHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateFrameBuffer__JIILtwilight_bgfx_TextureFormat_2
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyFrameBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/FrameBufferHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyFrameBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nvertexPack
 * Signature: ([FZLl33tlabs/twilight/bgfx/BGFX/Attrib;Ll33tlabs/twilight/bgfx/VertexDecl;JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nvertexPack
  (JNIEnv *, jobject, jfloatArray, jboolean, jobject, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nvertexUnpack
 * Signature: (FLl33tlabs/twilight/bgfx/BGFX/Attrib;Ll33tlabs/twilight/bgfx/VertexDecl;JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nvertexUnpack
  (JNIEnv *, jobject, jfloat, jobject, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nvertexConvert
 * Signature: (Ll33tlabs/twilight/bgfx/VertexDecl;JLl33tlabs/twilight/bgfx/VertexDecl;JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nvertexConvert
  (JNIEnv *, jobject, jobject, jlong, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nweldVertices
 * Signature: (JLl33tlabs/twilight/bgfx/VertexDecl;JIF)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_nweldVertices
  (JNIEnv *, jobject, jlong, jobject, jlong, jint, jfloat);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nimageSwizzleBgra8
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nimageSwizzleBgra8
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nimageRgba8Downsample2x2
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nimageRgba8Downsample2x2
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ngetRendererType
 * Signature: ()Ll33tlabs/twilight/bgfx/BGFX/RendererType;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ngetRendererType
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ninit
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ninit
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nshutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nshutdown
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nreset
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nreset
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nframe
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_BGFX_nframe
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ngetCaps
 * Signature: ()Ll33tlabs/twilight/bgfx/BGFX/Caps;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_BGFX_ngetCaps
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nalloc
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_BGFX_nalloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncopy
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_BGFX_ncopy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nmakeRef
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_BGFX_nmakeRef
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetDebug
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetDebug
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndbgTextClear
 * Signature: (SZ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndbgTextClear
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndbgTextPrintf
 * Signature: (IISLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndbgTextPrintf
  (JNIEnv *, jobject, jint, jint, jshort, jstring);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateIndexBuffer
 * Signature: (Ljava/nio/ByteBuffer;)Ll33tlabs/twilight/bgfx/BGFX/IndexBufferHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateIndexBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyIndexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/IndexBufferHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyIndexBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateVertexBuffer
 * Signature: (Ljava/nio/ByteBuffer;Ll33tlabs/twilight/bgfx/VertexDecl;)Ll33tlabs/twilight/bgfx/BGFX/VertexBufferHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateVertexBuffer
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/VertexBufferHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyVertexBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateDynamicIndexBuffer
 * Signature: (J)Ll33tlabs/twilight/bgfx/BGFX/DynamicIndexBufferHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateDynamicIndexBuffer__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateDynamicIndexBuffer
 * Signature: (Ljava/nio/ByteBuffer;)Ll33tlabs/twilight/bgfx/BGFX/DynamicIndexBufferHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateDynamicIndexBuffer__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nupdateDynamicIndexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/DynamicIndexBufferHandle;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nupdateDynamicIndexBuffer
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyDynamicIndexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/DynamicIndexBufferHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyDynamicIndexBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateDynamicVertexBuffer
 * Signature: (Ljava/nio/ByteBuffer;Ll33tlabs/twilight/bgfx/VertexDecl;)Ll33tlabs/twilight/bgfx/BGFX/DynamicVertexBufferHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateDynamicVertexBuffer
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nupdateDynamicVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/DynamicVertexBufferHandle;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nupdateDynamicVertexBuffer
  (JNIEnv *, jobject, jint, jint, jint, jobject);



/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyDynamicVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/DynamicVertexBufferHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyDynamicVertexBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncheckAvailTransientIndexBuffer
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_twilight_bgfx_BGFX_ncheckAvailTransientIndexBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncheckAvailTransientVertexBuffer
 * Signature: (JLl33tlabs/twilight/bgfx/VertexDecl;)Z
 */
JNIEXPORT jboolean JNICALL Java_twilight_bgfx_BGFX_ncheckAvailTransientVertexBuffer
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncheckAvailInstanceDataBuffer
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_twilight_bgfx_BGFX_ncheckAvailInstanceDataBuffer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncheckAvailTransientBuffers
 * Signature: (JLl33tlabs/twilight/bgfx/VertexDecl;J)Z
 */
JNIEXPORT jboolean JNICALL Java_twilight_bgfx_BGFX_ncheckAvailTransientBuffers
  (JNIEnv *, jobject, jlong, jobject, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nallocTransientIndexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TransientIndexBuffer;J)V
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_BGFX_nallocTransientIndexBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nallocTransientVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TransientVertexBuffer;JLl33tlabs/twilight/bgfx/VertexDecl;)V
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_BGFX_nallocTransientVertexBuffer
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nallocInstanceDataBuffer
 * Signature: (JI)Ll33tlabs/twilight/bgfx/BGFX/InstanceDataBuffer;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_BGFX_nallocInstanceDataBuffer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateShader
 * Signature: (Ljava/nio/ByteBuffer;)Ll33tlabs/twilight/bgfx/BGFX/ShaderHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateShader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ngetShaderUniforms
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/ShaderHandle;Ll33tlabs/twilight/bgfx/BGFX/UniformHandle;I)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ngetShaderUniforms
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyShader
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/ShaderHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyShader
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateProgram
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/ShaderHandle;Ll33tlabs/twilight/bgfx/BGFX/ShaderHandle;Z)Ll33tlabs/twilight/bgfx/BGFX/ProgramHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateProgram
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyProgram
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/ProgramHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncalcTextureSize
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TextureInfo;IIISLl33tlabs/twilight/bgfx/BGFX/TextureFormat;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ncalcTextureSize
  (JNIEnv *, jobject, jobject, jint, jint, jint, jshort, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateTexture
 * Signature: (Ljava/nio/ByteBuffer;JSLl33tlabs/twilight/bgfx/BGFX/TextureInfo;)Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateTexture
  (JNIEnv *, jobject, jobject, jlong, jshort, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateTexture2D
 * Signature: (IISLl33tlabs/twilight/bgfx/BGFX/TextureFormat;JLjava/nio/ByteBuffer;)Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateTexture2D
  (JNIEnv *, jobject, jint, jint, jshort, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateTexture3D
 * Signature: (IIISLl33tlabs/twilight/bgfx/BGFX/TextureFormat;JLjava/nio/ByteBuffer;)Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateTexture3D
  (JNIEnv *, jobject, jint, jint, jint, jshort, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateTextureCube
 * Signature: (ISLl33tlabs/twilight/bgfx/BGFX/TextureFormat;JLjava/nio/ByteBuffer;)Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateTextureCube
  (JNIEnv *, jobject, jint, jshort, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nupdateTexture2D
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;SIIIILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nupdateTexture2D
  (JNIEnv *, jobject, jint, jshort, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nupdateTexture3D
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;SIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nupdateTexture3D
  (JNIEnv *, jobject, jint, jshort, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nupdateTextureCube
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;SSIIIILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nupdateTextureCube
  (JNIEnv *, jobject, jint, jshort, jshort, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyTexture
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ncreateUniform
 * Signature: (Ljava/lang/String;Ll33tlabs/twilight/bgfx/BGFX/UniformType;I)Ll33tlabs/twilight/bgfx/BGFX/UniformHandle;
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_ncreateUniform
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndestroyUniform
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/UniformHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndestroyUniform
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewName
 * Signature: (SLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewName
  (JNIEnv *, jobject, jshort, jstring);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewRect
 * Signature: (SIIII)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewRect
  (JNIEnv *, jobject, jshort, jint, jint, jint, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewRectMask
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewRectMask
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewScissor
 * Signature: (SIIII)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewScissor
  (JNIEnv *, jobject, jshort, jint, jint, jint, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewScissorMask
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewScissorMask
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewClear
 * Signature: (SSJFS)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewClear
  (JNIEnv *, jobject, jshort, jshort, jlong, jfloat, jshort);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewClearMask
 * Signature: (JSJFS)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewClearMask
  (JNIEnv *, jobject, jlong, jshort, jlong, jfloat, jshort);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewSeq
 * Signature: (SZ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewSeq
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewSeqMask
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewSeqMask
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewFrameBuffer
 * Signature: (SLl33tlabs/twilight/bgfx/BGFX/FrameBufferHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewFrameBuffer
  (JNIEnv *, jobject, jshort, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewFrameBufferMask
 * Signature: (JLl33tlabs/twilight/bgfx/BGFX/FrameBufferHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewFrameBufferMask
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewTransform
 * Signature: (SJJS)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewTransform
  (JNIEnv *, jobject, jshort, jfloatArray, jfloatArray);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetViewTransformMask
 * Signature: (JJJS)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetViewTransformMask
  (JNIEnv *, jobject, jlong, jlong, jlong, jshort);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetMarker
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetMarker
  (JNIEnv *, jobject, jstring);

static uint64_t bgfx_blend_func(uint64_t _srcRGB, uint64_t _dstRGB, uint64_t _srcA, uint64_t _dstA);

JNIEXPORT jlong JNICALL Java_twilight_bgfx_BGFX_ndoBlendFunc
  (JNIEnv* env, jobject self, jlong srcRGB, jlong dstRGB, jlong srcA, jlong dstA);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetState
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetState
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetStencil
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetStencil
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetScissor
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_BGFX_nsetScissor__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetScissor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetScissor__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetTransform
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_BGFX_nsetTransform
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetUniform
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/UniformHandle;JI)V
 */
JNIEXPORT void Java_twilight_bgfx_BGFX_nsetUniform__IJI
  (JNIEnv *, jobject, jint, jlong, jint);

JNIEXPORT void Java_twilight_bgfx_BGFX_nsetUniform__IFI
  (JNIEnv *, jobject, jint, jfloat, jint);

JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetUniform__I_3FI
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetIndexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/IndexBufferHandle;JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetIndexBuffer__Ltwilight_bgfx_buffers_IndexBuffer_2JJ
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetIndexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/DynamicIndexBufferHandle;JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetIndexBuffer__Ltwilight_bgfx_buffers_DynamicIndexBuffe_2JJ
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetIndexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TransientIndexBuffer;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetIndexBuffer__Ltwilight_bgfx_buffers_TransientIndexBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetIndexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TransientIndexBuffer;JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetIndexBuffer__Ltwilight_bgfx_buffers_TransientIndexBuffer_2JJ
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/VertexBufferHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetVertexBuffer__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/VertexBufferHandle;JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetVertexBuffer__Ltwilight_bgfx_buffers_VertexBuffer_2JJ
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/DynamicVertexBufferHandle;J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetVertexBuffer__Ltwilight_bgfx_buffers_DynamicVertexBuffer_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TransientVertexBuffer;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetVertexBuffer__Ltwilight_bgfx_buffers_TransientVertexBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetVertexBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/TransientVertexBuffer;JJ)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetVertexBuffer__Ltwilight_bgfx_buffers_TransientVertexBuffer_2JJ
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetInstanceDataBuffer
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/InstanceDataBuffer;I)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetInstanceDataBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetProgram
 * Signature: (Ll33tlabs/twilight/bgfx/BGFX/ProgramHandle;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetTexture
 * Signature: (SLl33tlabs/twilight/bgfx/BGFX/UniformHandle;Ll33tlabs/twilight/bgfx/BGFX/TextureHandle;J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsetTexture__SIIJ
  (JNIEnv *, jobject, jshort, jint, jint, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsetTexture
 * Signature: (SLl33tlabs/twilight/bgfx/BGFX/UniformHandle;Ll33tlabs/twilight/bgfx/BGFX/FrameBufferHandle;SJ)V
 */
JNIEXPORT void Java_twilight_bgfx_BGFX_nsetTexture__SIISJ
  (JNIEnv *, jobject, jshort, jint, jint, jshort, jlong);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsubmit
 * Signature: (SI)J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_BGFX_nsubmit
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsubmitMask
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_BGFX_nsubmitMask
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    ndiscard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_ndiscard
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_BGFX
 * Method:    nsaveScreenShot
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_BGFX_nsaveScreenShot
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
