/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_nanovg_NanoVG */

#ifndef _Included_twilight_bgfx_nanovg_NanoVG
#define _Included_twilight_bgfx_nanovg_NanoVG
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_ninitJVMMetadata
  (JNIEnv *, jobject);

JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgCreate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgBeginFrame
 * Signature: (JIIFI)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgBeginFrame
  (JNIEnv *, jobject, jlong, jint, jint, jfloat, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgEndFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgEndFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRGB
 * Signature: (CCC)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRGB
  (JNIEnv *, jobject, jchar, jchar, jchar);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRGBf
 * Signature: (FFF)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRGBf
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRGBA
 * Signature: (CCCC)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRGBA
  (JNIEnv *, jobject, jchar, jchar, jchar, jchar);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRGBAu
 * Signature: (I)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRGBAu
  (JNIEnv *, jobject, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRGBAf
 * Signature: (FFFF)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRGBAf
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgLerpRGBA
 * Signature: (Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;F)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgLerpRGBA
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTransRGBA
 * Signature: (Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;C)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTransRGBA
  (JNIEnv *, jobject, jobject, jchar);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTransRGBAf
 * Signature: (Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;F)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTransRGBAf
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgHSL
 * Signature: (FFF)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgHSL
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgHSLA
 * Signature: (FFFC)Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgHSLA
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jchar);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgSave
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgSave
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRestore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRestore
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgReset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgStrokeColor
 * Signature: (JLl33tlabs/twilight/bgfx/nanovg/NVGcolor;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgStrokeColor
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgStrokePaint
 * Signature: (JLl33tlabs/twilight/bgfx/nanovg/NVGpaint;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgStrokePaint
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgFillColor
 * Signature: (JLl33tlabs/twilight/bgfx/nanovg/NVGcolor;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgFillColor
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgFillPaint
 * Signature: (JLl33tlabs/twilight/bgfx/nanovg/NVGpaint;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgFillPaint
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgMiterLimit
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgMiterLimit
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgStrokeWidth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgStrokeWidth
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgLineCap
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgLineCap
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgLineJoin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgLineJoin
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgResetTransform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgResetTransform
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTransform
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTransform
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTranslate
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTranslate
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRotate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRotate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgScale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgScale
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgCreateImage
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgCreateImage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgCreateImageMem
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgCreateImageMem
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgCreateImageRGBA
 * Signature: (JIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgCreateImageRGBA
  (JNIEnv *, jobject, jlong, jint, jint, jstring);

JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgCreateImageFromHandle
  (JNIEnv* env, jobject self, jlong ctx, jint handle);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgUpdateImage
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgUpdateImage
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgImageSize
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgImageSize
  (JNIEnv *, jobject, jlong, jint, jint, jint);

JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgDelete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgDeleteImage
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgDeleteImage
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgLinearGradient
 * Signature: (JFFFFLl33tlabs/twilight/bgfx/nanovg/NVGcolor;Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;)Ll33tlabs/twilight/bgfx/nanovg/NVGpaint;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgLinearGradient
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jobject, jobject);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgBoxGradient
 * Signature: (JFFFFFFLl33tlabs/twilight/bgfx/nanovg/NVGcolor;Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;)Ll33tlabs/twilight/bgfx/nanovg/NVGpaint;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgBoxGradient
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jobject, jobject);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRadialGradient
 * Signature: (JFFFFLl33tlabs/twilight/bgfx/nanovg/NVGcolor;Ll33tlabs/twilight/bgfx/nanovg/NVGcolor;)Ll33tlabs/twilight/bgfx/nanovg/NVGpaint;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRadialGradient
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jobject, jobject);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgImagePattern
 * Signature: (JFFFFFII)Ll33tlabs/twilight/bgfx/nanovg/NVGpaint;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgImagePattern
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgScissor
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgScissor
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgResetScissor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgResetScissor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgBeginPath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgBeginPath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgMoveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgMoveTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgLineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgLineTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgBezierTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgBezierTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgArcTo
 * Signature: (JFFFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgArcTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgClosePath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgClosePath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgPathWinding
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgPathWinding
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgArc
 * Signature: (JFFFFFI)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgArc
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgRoundedRect
 * Signature: (JFFFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgRoundedRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgEllipse
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgEllipse
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgCircle
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgCircle
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgFill
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgFill
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgStroke
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgStroke
  (JNIEnv *, jobject, jlong);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgCreateFont
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgCreateFont
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgCreateFontMem
 * Signature: (JLjava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgCreateFontMem
  (JNIEnv *, jobject, jlong, jstring, jobject, jint, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgFindFont
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgFindFont
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgFontSize
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgFontSize
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgFontBlur
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgFontBlur
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextLetterSpacing
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextLetterSpacing
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextLineHeight
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextLineHeight
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextAlign
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextAlign
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgFontFaceId
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgFontFaceId
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgFontFace
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgFontFace
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgText
 * Signature: (JFFLjava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgText
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jstring, jstring);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextBox
 * Signature: (JFFFLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextBox
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jstring, jstring);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextBounds
 * Signature: (JFFLjava/lang/String;Ljava/lang/String;F)F
 */
JNIEXPORT jfloat JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextBounds
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jstring, jstring, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextBoxBounds
 * Signature: (JFFFLjava/lang/String;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextBoxBounds
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jstring, jstring, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextGlyphPositions
 * Signature: (JFFLjava/lang/String;Ljava/lang/String;Ll33tlabs/twilight/bgfx/nanovg/NVGglyphPosition;I)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextGlyphPositions
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jstring, jstring, jobject, jint);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextMetrics
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextMetrics
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     twilight_bgfx_nanovg_NanoVG
 * Method:    n_nvgTextBreakLines
 * Signature: (JLjava/lang/String;Ljava/lang/String;FLl33tlabs/twilight/bgfx/nanovg/NVGtextRow;I)I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_nanovg_NanoVG_nnvgTextBreakLines
  (JNIEnv *, jobject, jlong, jstring, jstring, jfloat, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
