/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_buffers_TransientIndexBuffer */

#ifndef _Included_twilight_bgfx_buffers_TransientIndexBuffer
#define _Included_twilight_bgfx_buffers_TransientIndexBuffer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_twilight_bgfx_buffers_TransientIndexBuffer_initJVMMetadata
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_TransientIndexBuffer
 * Method:    getData
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_buffers_TransientIndexBuffer_nGetData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
