/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_window_Window */

#ifndef _Included_twilight_bgfx_window_Window
#define _Included_twilight_bgfx_window_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     twilight_bgfx_window_Window
 * Method:    nSetPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_window_Window_nSetPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     twilight_bgfx_window_Window
 * Method:    nGetWindowRect
 * Signature: ()Ll33tlabs/twilight/bgfx/window/Window/Rect;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_window_Window_nGetWindowRect
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_Window
 * Method:    nSetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_window_Window_nSetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     twilight_bgfx_window_Window
 * Method:    nSetVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_twilight_bgfx_window_Window_nSetVisible
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
