/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_PlatformUtil */

#ifndef _Included_twilight_bgfx_PlatformUtil
#define _Included_twilight_bgfx_PlatformUtil
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_twilight_bgfx_util_PlatformUtil_nsetPlatformWindow(JNIEnv*, jobject, jlong, jlong, jlong);
void setPlatformWindow(long ndt, long nwh, long context);

#ifdef __cplusplus
}
#endif
#endif
