/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_window_Window_Rect */

#ifndef _Included_twilight_bgfx_window_Window_Rect
#define _Included_twilight_bgfx_window_Window_Rect
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
