/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_window_X11Display */

#ifndef _Included_twilight_bgfx_window_X11Display
#define _Included_twilight_bgfx_window_X11Display
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nSetCursor
  (JNIEnv* env, jobject self, jlong cursorPtr);

JNIEXPORT jlong JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nCreatePlatformCursor
  (JNIEnv* env, jobject self, jint index);


/*
 * Class:     twilight_bgfx_window_X11Display
 * Method:    nIsValid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nIsValid
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Display
 * Method:    nUpdate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nUpdate
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Display
 * Method:    nCreateDisplay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nCreateDisplay
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Display
 * Method:    nGetDPI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nGetDPI
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Display
 * Method:    nGetWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nGetWidth
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Display
 * Method:    nGetHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nGetHeight
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Display
 * Method:    nGetPhysicalWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nGetPhysicalWidth
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_window_X11Display
 * Method:    nGetPhysicalHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_twilight_bgfx_window_sdl_SDLDisplay_nGetPhysicalHeight
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
