/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twilight_bgfx_buffers_TransientVertexBuffer */

#ifndef _Included_twilight_bgfx_buffers_TransientVertexBuffer
#define _Included_twilight_bgfx_buffers_TransientVertexBuffer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_twilight_bgfx_buffers_TransientVertexBuffer_initJVMMetadata
  (JNIEnv *, jobject);

/*
 * Class:     twilight_bgfx_TransientVertexBuffer
 * Method:    getData
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_twilight_bgfx_buffers_TransientVertexBuffer_nGetData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
