#
# Determine the target platform and architecture
# 

if(NOT DEFINED TARGET_ARCH)
    message("No target arch specified, autodetecting current platform...")
    message("Note that nacl, pnacl, emscipten and other cross compiler targets will never be selected.")

	# default to 64-bit Linux
    set(TARGET_PLAT "Linux")
    set(TARGET_ARCH "linux-x64")

    if (CMAKE_SIZEOF_VOID_P MATCHES "8")
        if(UNIX)
            if(_ANDROID_)
                set(TARGET_PLAT "Android")
                set(TARGET_ARCH "android-armv7")
            else(_ANDROID_)
                if(APPLE) 
                    if(_IOS_)
                        set(TARGET_PLAT "iOS")
                        set(TARGET_ARCH "ios-x64")
                     else(_IOS_)
                        set(TARGET_PLAT "MacOSX")
                        set(TARGET_ARCH "macosx-x64")
                     endif(_IOS_)
                else(APPLE)
                    if(_NACL_)
                        set(TARGET_PLAT "NativeClient")
                        set(TARGET_ARCH "nacl-linux-x64")
                    else(_NACL_)
                        set(TARGET_PLAT "Linux")
                        set(TARGET_ARCH "linux-x64")
                        set(_LINUX_ ON)
                    endif(_NACL_)
                endif(APPLE)
            endif(_ANDROID_)
        else(UNIX)
            if(WIN32)
                set(TARGET_PLAT "Windows")
                set(TARGET_ARCH "win-x64")
            endif(WIN32)
        endif(UNIX)
    else(CMAKE_SIZEOF_VOID_P MATCHES "8")
        if(UNIX)
            if(_ANDROID_)
                set(TARGET_PLAT "Android")
                set(TARGET_ARCH "android-armv7")
            else(_ANDROID_)
                if(APPLE) 
                    if(_IOS_)
                        set(TARGET_PLAT "iOS")
                        set(TARGET_ARCH "ios-armv7")
                     else(_IOS_)
                        set(TARGET_PLAT "MacOSX")
                        set(TARGET_ARCH "macosx-x86")
                     endif(_IOS_)
                else(APPLE)
                    if(_NACL_)
                        set(TARGET_PLAT "NativeClient")
                        set(TARGET_ARCH "nacl-linux-x86")
                    else(_NACL_)
                        set(TARGET_ARCH "linux-x86")
                    endif(_NACL_)
                endif(APPLE)
            endif(_ANDROID_)
        else(UNIX)
            if(WIN32)
                set(TARGET_PLAT "Windows")
                set(TARGET_ARCH "win-x86")
            endif(WIN32)
        endif(UNIX)
    endif (CMAKE_SIZEOF_VOID_P MATCHES "8")
endif(NOT DEFINED TARGET_ARCH)

message("Twilight BGFX Target -- Building for ${TARGET_PLAT}, arch name: ${TARGET_ARCH}")

add_definitions( -DTWILIGHT_BGFX_${TARGET_ARCH} )